name: param_ens_gen
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - xarray
  - pyyaml
  - scipy
  - jupyterlab
  - ipykernel
  - pip
  - tqdm
  - netcdf4
  # --- dev / test ---
  - black
  - pylint
  - pytest>=8
  - pytest-cov
  - pytest-mock
  - pip:
    - -e .